services:
  web:

    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "pnpm install && pnpm run dev"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true